module.exports = [
    {
        name: "Farriday",
        description: "Farriday was listed as a super senior at the shelter. However, their age guesstimate was mostly based on his horrible teeth. Because he'd been a stray and his mouth was in bad shape, he was thin and appeared frail and elderly. Despite his condition, Kitty Devore Rescue saved this old man and expected hospice care for the rest of his life. But fate had another destiny in store for him.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/46822303/1/?bust=1576099966&width=560",
        breeds: "Tabby",
        colors: String,
        age: 10,
        sex: "male",
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: true,
        shots_current: true,
        children: false,
        dogs: false,
        cats: false,
    },
    {
        name: "Frypan",
        description: "This Frypan has that sweet demeanor & look like my 'Frypan', so I wanted to have this dog have his name, too. He is 17 lbs & older..his teeth are so rotten & one is cracked that our doctor (who I want to thank Heritage An. Hospital for seeing him today due to discovering how much pain he was in) is getting him in next week for dental & neuter. Frypan has ear & skin infections, is positive for one tick disease (was covered in ticks) is probably anemic but blood work is not up yet. He has gotten 2 baths tonight, alot of love from the transporters & his new fosters.",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47954594/1/?bust=1588987173&width=560",
        breeds: "Beagle",
        colors: "Tan and White",
        age: 7,
        size: "medium",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: false,
        dogs: false,
        cats: false,
    },
    {
        name: "Thimble",
        description: "Thimble was brought to Animal Haven after his owner unfortunately passed away from COVID-19. He's understandably a bit confused after everything that has happened in the last few weeks and is taking some time to settle in. This gentle boy just needs a little time to mentally heal after such heartbreak. Thimble is a sweet but slightly nervous boy looking for his person to keep him company for the rest of his years. If you're open to giving this senior a new loving home, please contact Animal Haven to meet him.",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47940804/1/?bust=1588808134&width=560",
        breeds: "Mixed Breed",
        age: 5,
        size: 'extra-medium',
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: false,
    },
    {
        name: "Gwen Stefanchi",
        description: "Gwen Sfefanchi (Steffi) was surrendered to the shelter by her owner. She had been neglected with overgrown nails and some badly infected teeth, and we think may have suffered abuse as well. After extensive dental work, immediately upon getting to The REAL Bark, she felt so much better and was able to go to her foster home where she is learning to trust again. ",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47833976/2/?bust=1587335298&width=560",
        breeds: "Chihuahua-mix",
        age: 8,
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: true,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Holly",
        description: "Holly is a gorgeous Heeler/Lab/Shepherd/Terrier beautifully and uniquely mixed dog. She is a beauty, but the most attractive thing about her is her kind heart and sweet personality. She is super friendly with everyone and she has never met a stranger. Everyone is her friend. She loves kids and loves to cuddle. She does OK with other submissive dogs (with the right leadership), but prefers to be the only dog at home. She is not very good with cats and prefers a home without them (she gets overly excited over cats).",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47921153/1/?bust=1588539836&width=560",
        breeds: "Heeler/Lab",
        age: 6,
        size: "extra-medium",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: false,
    },
    {
        name: "Mouser/Ratter Cat",
        description: "Do you need a mouser in your garage, shop, warehouse, brewery, restaurant or greenhouse? Mouser cats are a natural, organic rodent control method that will spare you the need to use poisons for your mouse or rat problem.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/17795852/1/?bust=1436020190&width=560",
        breeds: "Tabby",
        age: "3",
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: false,
        cats: false,
    },
    {
        name: "Charity",
        description: "Meet Miss Charity! She is approximately 1 year old. Charity is extremely friendly, talkative, and seeks attention. She is good company and a loving companion. Charity has been spayed, current on her vaccines, FIV/FELV negative, microchipped, and on flea prevention. Her adoption fee is $85.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47893868/3/?bust=1588733152&width=560",
        breeds: "Tabby",
        age: 7,
        size: "small",
        spayedOrNeutered: false,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: false,
        cats: false,
    },
    {
        name: "Jazzy",
        description: "Spayed / neutered.",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47947880/1/?bust=1588965786&width=560",
        breeds: "Terrier mix",
        size: "medium",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Brooke",
        description: "Brooke started out in the local County Shelter ... beautiful from the day we first saw her, and so full of fun and mischief ! She loves EVERYTHING including but not limited to: Toys, Food, Sunshine, People, Other cats / kittens, dogs .... Brooke can find fun sitting still ! She is pure black, with fur so soft and supple it's like velvet, and she has beautiful, huge clear and expresive green eyes. Her face shape is more round and she's a solid, healthy girl too.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/45450023/1/?bust=1586423619&width=560",
        breeds: "mixed",
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Winnie",
        description: "Winnie came from a terrible hoarding situation and was in pretty rough shape when he was rescued. He has gotten healthy and his beautiful coat has filled out while he's been in foster care. Winnie is a sweet boy who is still getting used to life as a normal cat. He likes to be around people and likes to be petted but he will let you know when he's had enough. He loves to play and plays well by himself and with others. He is still learning how to trust and still gets nervous sometimes. Winnie came from a stressful situation where he did not have consistent food, care, or love. He will need a home with lots of love and patience to let him continue to blossom.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47854855/1/?bust=1587580076&width=560",
        breeds: "Maine Coon",
        size: "medium",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Tormund",
        description: "Greetings, wildlings, kneelers, and otherwise! Tormund Giantsbane, here. I go by many names—“Horn-blower,” “Breaker of Ice,” “Speaker to Gods”—but no matter what you call me, this amazing 1-year-old American Staffordshire Terrier is up for adoption, and that’s no lie!",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47812423/1/?bust=1586905238&width=560",
        breeds: "American Staffordshire Terrier",
        size: "extra-medium",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Oakley",
        description: "Personality wise, Oakley is a well-mannered dog with 50/50 with energy. He loves to lay at your feet while you work from the table or snooze on the rug while you're watching TV. He is respectful on not jumping on furniture but does need to be picked up into the car.",
        type: "dog",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47909306/1/?bust=1588536822&width=560",
        breeds: "Siberian Husky",
        size: "large",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Pretty Kitty",
        description: "Pretty Kitty is a 1 ½ yr old sweet female tabby with tortie coloring mixed in to her bunny soft fur. She’s got a little bit of “tortie-tude” toward other cats, but is super sweet and loving to her humans. Other cats are ok, as long as there aren’t too many and they are low key with enough space to allow her to find her own secret perch by herself.",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47823679/5/?bust=1588959906&width=560",
        breeds: "Tabby",
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    },
    {
        name: "Pudding",
        description: "Pudding was rescued from a terrible hoarding situation before Thanksgiving (which is why everyone has food names, lol) along with about 40 other cats. She was so sick and terrified we thought she was going to be the one cat we would have to place in a barn home. Boy were we wrong!!",
        type: "cat",
        photos: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/47786257/2/?bust=1586479957&width=560",
        breeds: "Mixed",
        size: "small",
        spayedOrNeutered: true,
        house_trained: true,
        special_needs: false,
        shots_current: true,
        children: true,
        dogs: true,
        cats: true,
    }
]